- title: Femtocell-based Testbed for Evaluating Future Cellular Networks
  authors:
  - Hakyung Jung
  - Ji Hoon Lee
  - Chulhyun Park
  - Youngbin Im
  - Taekyoung Kwon
  - Yanghee Choi
  publisher: International Conferences on Future Internet Technologies (CFI) 2008
  date: '2008-06-18'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:u5HHmVD_uO8C
  
  - title: Performance Evaluation in Combination of Wired and Wireless Mesh Networks
  authors:
  - Jin-Young Han
  - Hee-Dong Jung
  - Young-Bin Im
  - Jeong-Keun Lee
  - Ji-Ho Ryu
  - Tae-Kyoung Kwon
  - Yang-Hee Choi
  publisher: 'Journal of KIISE: Computing Practices and Letters 14 (8), 778-782, 2008'
  date: '2008-11-15'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:hqOjcs7Dif8C

- title: 'FIRM: Flow-based interference-aware route management in wireless mesh networks'
  authors:
  - Youngbin Im
  - Jeongkeun Lee
  - Jinyoung Han
  - Sung-Ju Lee
  - Taekyoung Kwon
  publisher: "IEEE Workshop on Wireless Mesh Networks (WiMesh) 2009"
  date: '2009-06-22'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:YsMSGLbcyi4C

- title: 'Vertical Handovers in Multiple Heterogeneous Wireless Networks: A Measurement Study for the Future Internet'
  authors:
  - Youngbin Im
  - Hakyung Jung
  - Ji Hoon Lee
  - Wonjun Yoo
  - Ted "Taekyoung" Kwon
  - Yanghee Choi
  publisher: "International Conference on Future Internet Technologies (CFI) 2010"
  date: '2010-06-16'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:qjMakFHDy7sC

- title: 'TUBE: Time-dependent pricing for mobile data'
  authors:
  - Sangtae Ha
  - Soumya Sen
  - Carlee Joe-Wong
  - Youngbin Im
  - Mung Chiang
  publisher: "ACM SIGCOMM 2012"
  date: '2012-08-13'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:W7OEmFMy1HYC

- title: 'MASERATI: Mobile Adaptive Streaming based on Environmental and Contextual Information'
  authors:
  - Dookyoon Han
  - Jinyoung Han
  - Youngbin Im
  - Myungchul Kwak
  - Ted "Taekyoung" Kwon
  - Yanghee Choi
  publisher: "ACM International Workshop on Wireless Network Testbeds, Experimental Evaluation and Characterization(WiNTECH)"
  date: '2013-09-30'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:u-x6o8ySG0sC

- title: 'AMUSE: Empowering Users for Cost-Aware Offloading with Throughput-Delay Tradeoffs'
  authors:
  - Youngbin Im
  - Carlee Joe-Wong
  - Sangtae Ha
  - Soumya Sen
  - Ted "Taekyoung" Kwon
  - Mung Chiang
  publisher: IEEE Transactions on Mobile Computing(TMC)
  date: '2016-05-01'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:2osOgNQ5qMEC

- title: A Performance Analysis of Incentive Mechanism for Cooperative Computing
  authors:
  - Carlee Joe-Wong
  - Youngbin Im
  - Kyuyong Shin
  - Sangtae Ha
  publisher: "2016 IEEE 36th International Conference on Distributed Computing Systems (ICDCS)"
  date: '2016-06-27'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:9yKSN-GCB0IC

-title: Calibrating Time-variant, Device-specific Phase Noise for COTS WiFi Device
  authors:
  - Jincao Zhu,
  - Youngbin Im
  - Shivakant Mishra
  - Sangtae Ha
  publisher: ACM Conference on Embedded Network Sensor Systems Sensys 2017
  date: '2017-11-16'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:zYLM7Y9cAGgC

- title: 'SVC-TChain: Incentivizing Good Behavior in Layered P2P Video Streaming'
  authors:
  - Parisa Rahimzadeh
  - Carlee Joe-Wong
  - Kyuyong Shin
  - Youngbin Im
  - Jongdeog Lee
  - Sangtae Ha
  publisher: IEEE INFOCOM 2017-IEEE Conference on Computer Communications
  date: '2017-05-01'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:Y0pCki6q_DkC

- title: 'FluidMem: Memory as a Service for the Datacenter'
  authors:
  - Blake Caldwell
  - Youngbin Im
  - Sangtae Ha
  - Richard Han
  - Eric Keller
  publisher: arXiv preprint arXiv:1707.07780
  date: '2017-07-25'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:Tyk-4Ss8FVUC

- title: 'FLARE: Coordinated Rate Adaptation for HTTP Adaptive Streaming in Cellular Networks
    networks'
  authors:
  - Youngbin Im
  - Jinyoung Han
  - Ji Hoon Lee
  - Yoon Kwon
  - Carlee Joe-Wong
  - Taekyoung Kwon
  - Sangtae Ha
  publisher: "2017 IEEE 37th International Conference on Distributed Computing Systems (ICDCS)"
  date: '2017-06-05'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:d1gkVwhDpl0C

- title: Method and apparatus for assigning video bitrate in mobile communication system
  authors:
  - Hyungho Lee
  - Taekyoung Kwon
  - Jicheol Lee
  - Youngbin Im
  - Hanna Lim
  - Taejoong Chung
  - Dookyoon Han
  publisher: United States Patent US9398337 B2
  date: '2016-07-19'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:WF5omc3nYNoC

- title: A Practical Evaluation of Rate Adaptation Algorithms in HTTP-based Adaptive Streaming
  authors:
  - Ibrahim Ayad
  - Youngbin Im
  - Eric Keller
  - Sangtae Ha
  publisher: Elsevier Computer Networks
  date: '2018-03-14'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:ufrVoPGSRksC

- title: 'SNN-Cache: A Practical Machine Learning-based Caching System Utilizing the Inter-relationships of Requests'
  authors:
  - Youngbin Im
  - Prasanth Prahladan
  - Tae Hwan Kim
  - Yong Geun Hong
  - Sangtae Ha
  publisher: 2018 52nd Annual Conference on Information Sciences and Systems (CISS)
  date: '2018-03-21'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:_FxGoFyzp5QC

- title: 'Development of an EPIC Parallel Computing Framework to Facilitate Regional/Global Gridded Crop Modeling with Multiple Scenarios: A Case Study of the United States'
  authors:
  - Won Seok Jang
  - Yonggwan Lee
  - JJason C Neff
  - Youngbin Im
  - Sangtae Ha
  - Luca Doro
  publisher: Computers and Electronics in Agriculture
  date: '2019-03-01'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:roLk4NBRz8UC

- title: 'I Sent It: Where Does Slow Data Go to Wait?'
  authors:
  - Youngbin Im
  - Parisa Rahimzadeh
  - Brett Shouse
  - Shinik Park
  - Carlee Joe-Wong
  - Kyunghan Lee
  - Sangtae Ha
  publisher: The Fourteenth EuroSys Conference 2019 
  date: '2019-03-25'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:UebtZRa9Y70C

- title: Modeling MPTCP performance
  authors:
  - Jinsung Lee
  - Youngbin Im
  - Jeongkeun Lee
  publisher: IEEE communications letters
  date: '2019-02-10'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:Se3iqnhoufwC

- title: 'CASTLE over the Air: Distributed Scheduling for Cellular Data Transmissions'
  authors:
  - Jihoon Lee
  - Jinsung Lee
  - Youngbin Im
  - Sandesh Dhawaskar Sathyanarayana
  - Parisa Rahimzadeh
  - Xiaoxi Zhang
  - Max Hollingworth
  - Carlee Joe-Wong
  - Dirk Grunwald
  - Sangtae Ha
  publisher: The 17th Annual International Conference on Mobile Systems, Applications, and Services (ACM MobiSys 2019)
  date: '2019-06-12'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:8k81kl-MbHgC

- title: 'CASTLE over the Air: Distributed Scheduling for Cellular Data Transmissions (demo)'
  authors:
  - Sandesh Dhawaskar Sathyanarayana
  - Jihoon Lee
  - Jinsung Lee
  - Youngbin Im
  - Parisa Rahimzadeh
  - Xiaoxi Zhang
  - Max Hollingworth
  - Carlee Joe-Wong
  - Dirk Grunwald
  - Sangtae Ha
  publisher: The 17th Annual International Conference on Mobile Systems, Applications, and Services (ACM MobiSys 2019)
  date: '2019-06-12'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:8k81kl-MbHgC

- title: 'This is Your President Speaking: Spoofing Alerts in 4G LTE Networks'
  authors:
  - Gyuhong Lee
  - Jihoon Lee
  - Jinsung Lee
  - Youngbin Im
  - Max Hollingsworth
  - Eric Wustrow
  - Dirk Grunwald
  - Sangtae Ha
  publisher: The 17th Annual International Conference on Mobile Systems, Applications, and Services (ACM MobiSys 2019)
  date: '2019-06-12'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:5nxA0vEk-isC

- title: 'This is Your President Speaking: Spoofing Alerts in 4G LTE Networks (demo)'
  authors:
  - Max Hollingsworth
  - Gyuhong Lee
  - Jihoon Lee
  - Jinsung Lee
  - Youngbin Im
  - Eric Wustrow
  - Dirk Grunwald
  - Sangtae Ha
  publisher: The 17th Annual International Conference on Mobile Systems, Applications, and Services (ACM MobiSys 2019)
  date: '2019-06-12'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:0EnyYjriUFMC

- title: "DEMO-This is Your President Speaking: Spoofing Alerts in 4G LTE Networks"
  authors:
  - Max Hollingsworth
  - Gyuhong Lee
  - Jeongkeun Lee
  - Jeongkeun Lee
  - Youngbin Im
  - Eric Wustrow
  - Dirk Grunwald
  - Sangtae Ha
  publisher: The 17th Annual International Conference on Mobile Systems, Applications, and Services (ACM MobiSys 2019)
  date: '2019-06-12'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:4DMP91E08xMC


- title: 'ECHO: Efficiently Overbooking Applications to Create a Highly Available Cloud'
  authors:
  - Parisa Rahimzadeh
  - Youngbin Im
  - Gueyoung Jung
  - Carlee Joe-Wong
  - Sangtae Ha
  publisher: "2019 IEEE 39th International Conference on Distributed Computing Systems (ICDCS)"
  date: '2019-07-07'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:Zph67rFs4hoC

- title: Optimal Learning-Based Network Protocol Selection
  authors:
  - Xiaoxi Zhang
  - Siqi Chen
  - Youngbin Im
  - Maria Gorlotova
  - Sangtae Ha
  - Carlee Joe-Wong
  publisher: IEEE/ACM ISCA Workshop on Machine Learning for Systems 2019
  date: '2019-06-23'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:KlAtU1dfN6UC

- title: 'Towards Automated Network Management: Learning the Optimal Protocol Selction'
  authors:
  - Xiaoxi Zhang
  - Siqi Chen
  - Youngbin Im
  - Maria Gorlotova
  - Sangtae Ha
  - Carlee Joe-Wong
  publisher: 2019 IEEE 27th International Conference on Network Protocols (ICNP)
  date: '2019-10-08'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:kNdYIx-mwKoC

- title: Integrated Large-Scale Modeling Framework for N2O Emissions Estimation in an Agricultural Field using Parallel Computing.
  authors:
  - Won Seok Jang
  - Jason Neff
  - Youngbin Im
  - Jongyoon Park
  - Jeffery Herrick
  publisher: Geophysical Research Abstracts 21, 2019
  date: '2019-01-01'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:YOwf2qJgpHMC

- title: 'FluidMem: Full Flexible and Fast Memory Disaggregation for the Cloud'
  authors:
  - Blake Caldwell
  - Sepideh Goodarzy
  - Sangtae Ha
  - Richard Han
  - Eric Keller
  - Eric Rozner
  - Youngbin Im
  publisher: "2020 IEEE 40th International Conference on Distributed Computing Systems (ICDCS)"
  date: '2020-11-29'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:_kc_bZDykSQC

- title: 'SPARCLE: Streaming Processing Applications over Dispersed Computing Networks'
  authors:
  - Parisa Rahimzadeh
  - Jeongkeun Lee
  - Youngbin Im
  - Siun-Chuon Mau
  - Eric C Lee
  - Bradford O Smith
  - Fatemah Al-Duoli
  - Carlee Joe-Wong
  - Sangtae Ha
  publisher: "2020 IEEE 40th International Conference on Distributed Computing Systems (ICDCS)"
  date: '2020-11-29'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:qxL8FJ1GzNc

- title: Method for providing video streaming service and mobile device for same
  authors:
  - Hyung-Ho Lee
  - Taekyoung Kwon
  - Han-Na Lim
  - Dookyoon Han
  - Ji-Cheol Lee
  - Youngbin Im
  - Taejoong Chung
  publisher: (United States Patent US10631030 B2) 
  date: '2020-04-21'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:eQOLeE2rZwMC

- title: Method and apparatus for controlling send buffer of transmission control protocol in communication system
  authors:
  - Jin-Sung Lee
  - Young-Bin Im
  - Sangtae Ha
  - Sang-Jun Moon 
  - Jung-Shin Park
  - Ji-Cheol Lee
  - Joo-hyung Lee
  publisher: (United States Patent US10560389 B2)
  date: '2020-02-11'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:IjCSPb-OGe4C

- title: The Hidden Costs of Land Degradation in U.S. Maize Agriculture
  authors:
  - Won Seok Jang
  - Jason Neff
  - Youngbin Im
  - Luca Doro
  - JE Herrick
  publisher: Earth's Future
  date: '2021-02-12'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:aqlVkmm33-oC

- title: 'ECLAT: An ECN marking system for latency guarantee in cellular networks'
  authors:
  - Junseon Kim
  - Youngbin Im
  - Kyunghan Lee
  publisher: IEEE INFOCOM 2021-IEEE Conference on Computer Communications
  date: '2021-05-10'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:Wp0gIr-vW9MC

- title: 'Network latency analysis using eBPF'
  authors:
  - Shaikhitdin Nezametdinov
  - Youngbin Im
  publisher: KICS Summer Conference 2021
  date: '2022-06-16'
  link: https://www.dbpia.co.kr/pdf/pdfView.do?nodeId=NODE10586969&googleIPSandBox=false&mark=0&ipRange=false&b2cLoginYN=false&aiChatView=A&readTime=5-10&isPDFSizeAllowed=true&accessgl=Y&language=ko_KR&hasTopBanner=true

- title: Securing the wireless emergency alerts system
  authors:
  - Jihoon Lee
  - Gyuhong Lee
  - Jinsung Lee
  - Youngbin Im
  - Max Hollingsworth
  - Eric Wustrow
  - Dirk Grunwald
  - Sangtae Ha
  publisher: Communications of the ACM 2021
  date: '2021-09-22'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:9ZlFYXVOiuMC

- title: 'An analysis of the DPDK performance on SmartNICs using eBPF'
  authors:
  - Bongwon Lee
  - Youngbin Im
  publisher: KICS Fall Conference 2021
  date: '2022-06-16'
  link: https://www.dbpia.co.kr/pdf/pdfView.do?nodeId=NODE11022696

- title: 'Modems: Optimizing edge computing migrations for user mobility'
  authors:
  - Taejin Kim
  - Sandesh Dhawaskar Sathyanarayana
  - Siqi Chen
  - Youngbin Im
  - Xiaoxi Zhang
  - Sangtae Ha
  - Carlee Joe-Wong
  publisher: IEEE Journal on Selected Areas in Communications
  date: '2022-12-21'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:mVmsd5A6BfQC

- title: Optimal network protocol selection for competing flows via online learning
  authors:
  - Xiaoxi Zhang
  - Siqi Chen
  - Yunfan Zhang
  - Youngbin Im
  - Maria Gorlotova
  - Sangtae Ha
  - Carlee Joe-Wong
  publisher: IEEE Transactions on Mobile Computing (TMC) 2022
  date: '2022-04-11'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:dhFuZR0502QC

- title: Enabling Delay-Guaranteed Congestion Control with One-Bit Feedback in Cellular Networks
  authors:
  - Junseon Kim
  - Youngbin Im
  - Kyunghan Lee
  publisher: IEEE/ACM Transactions on Networking (ToN) 2023
  date: '2023-06-16'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:L8Ckcad2t8MC

- title: 'An Empirical Study of 5G: Effect of Edge on Transport Protocol and Application Performance'
  authors:
  - Hyoyoung Lim
  - Jinsung Lee
  - Jongyun Lee
  - Sandesh Dhawaskar Sathyanarayana
  - Junseon Kim
  - Anh Nguyen
  - Kwang Taik Kim
  - Youngbin Im
  - Mung Chiang
  - Dirk Grunwald
  - Kyunghan Lee
  - Sangtae Ha
  publisher: IEEE Transactions on Mobile Computing (TMC) 2023
  date: '2023-05-12'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:7PzlFSSx8tAC

- title: 'Demo: Pricing by Timing for Mobile Data'
  authors:
  - Sangtae Ha
  - Soumya Sen
  - Carlee Joe-Wong
  - J Mifkovich
  - R Rill
  - Youngbin Im
  - D Butnariu
  - J Bawa
  - M. Chiang
  publisher: 'IEEE INFOCOM 2012-IEEE Conference on Computer Communications'
  date: '2012-03-25'
  link: https://scholar.google.com/citations?view_op=view_citation&hl=en&user=oktgJK8AAAAJ&pagesize=100&citation_for_view=oktgJK8AAAAJ:UeHWp8X0CEIC

  - title: Demo: Pricing by Timing for Mobile Data
  authors:
  - Sangtae Ha
  - Soumya Sen
  - Carlee Joe-Wong
  - J Mifkovich
  - R Rill
  - Youngbin Im
  - D Butnariu
  - J Bawa
  - M. Chiang
  publisher: 'RBP: RSS-based Prediction of Carrier Sense and Interference in 802.11 Networks'
  date: '2007-08-20'
  link: https://ieeexplore.ieee.org/abstract/document/4292861/authors#authors
